<a href="https://colab.research.google.com/github/Shivasaireddy-prog/shivasai/blob/main/untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# ndarray
arr = np.array([1, 2, 3])
print(type(arr))
mat = np.matrix([[1, 2], [3, 4]])
print(type(mat))

print(type(arr[0]))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>
<class 'numpy.int64'>


In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Multiplication
result_mult = arr1 * arr2
print("Multiplication:", result_mult)

# Division
result_div = arr1 / arr2
print("Division:", result_div)

# Power
result_pow = arr1 ** 2
print("Power:", result_pow)

Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


In [5]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# addition
result = arr1+arr2
print(result)



[5 7 9]


In [6]:
import numpy as np

arr = np.array([1, 2, 3])

# Sine of each element in the array
sin_result = np.sin(arr)
print("Sine:", sin_result)

# Natural log of each element in the array
log_result = np.log(arr)
print("Natural Log:", log_result)

# Base-2 log of each element in the array
log2_result = np.log2(arr)
print("Base-2 Log:", log2_result)

# Exponential of each element in the array
exp_result = np.exp(arr)
print("Exponential:", exp_result)

Sine: [0.84147098 0.90929743 0.14112001]
Natural Log: [0.         0.69314718 1.09861229]
Base-2 Log: [0.        1.        1.5849625]
Exponential: [ 2.71828183  7.3890561  20.08553692]
